[colors.normal]
black = "0x1e1e2e"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6a3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xbac2de"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 12
y = 10
